name: my_system
description: "إدارة الطيف - نظام إدارة الطلبات والتحاسبات"
publish_to: 'none'
version: 1.2.5+9

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  fl_chart: ^0.69.0
  path_provider: ^2.1.1
  file_picker: ^8.1.6
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.13.2
  excel: ^4.0.6
  screenshot: ^3.0.0
  package_info_plus: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/icon/
    - assets/images/background.jpg
