name: my_system_api
description: API Backend for My System
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  args: ^2.4.0
  sqlite3: ^2.1.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.0
